// Generated by `bal openapi -i specs/design/components/ticket-api/openapi.yaml
// --mode service --single-file`, then hand-implemented per the contract.
import ballerina/http;
import ballerina/log;

listener http:Listener ep0 = new (9090);

service / on ep0 {
    # Every ticket in the shared queue
    #
    # + return - returns can be any of following types
    # http:Ok (A page of tickets)
    # http:Unauthorized (Not signed in)
    resource function get tickets(Urgency? urgency, TicketStatus? status, int 'limit = 20, int offset = 0)
            returns inline_response_200|ErrorUnauthorized|error {
        int effectiveLimit = 'limit;
        if effectiveLimit > 100 {
            effectiveLimit = 100;
        }
        if effectiveLimit < 1 {
            effectiveLimit = 20;
        }
        int effectiveOffset = offset < 0 ? 0 : offset;

        string? urgencyFilter = urgency is Urgency ? urgency : ();
        string? statusFilter = status is TicketStatus ? status : ();

        TicketPage page = check listTicketRows(urgencyFilter, statusFilter, effectiveLimit, effectiveOffset);
        Ticket[] tickets = [];
        foreach TicketRow row in page.rows {
            Ticket ticket = check toApiTicket(row);
            tickets.push(ticket);
        }

        [string?, string?] links = buildPageLinks("/tickets", urgencyFilter, statusFilter, effectiveLimit,
            effectiveOffset, page.count);
        string? next = links[0];
        string? previous = links[1];

        inline_response_200 result = {count: page.count, data: tickets};
        if next is string {
            result.next = next;
        }
        if previous is string {
            result.previous = previous;
        }
        return result;
    }

    # A ticket's current urgency, draft reply and status
    #
    # + return - returns can be any of following types
    # http:Ok (The ticket)
    # http:NotFound (No such ticket)
    # http:Unauthorized (Not signed in)
    resource function get tickets/[string ticketId]() returns Ticket|ErrorNotFound|ErrorUnauthorized|error {
        TicketRow?|error found = fetchTicketRow(ticketId);
        if found is error {
            return found;
        }
        if found is () {
            return <ErrorNotFound>{body: {code: 404, message: "no such ticket"}};
        }
        Ticket ticket = check toApiTicket(found);
        return ticket;
    }

    # A ticket's full history, in order
    #
    # + return - returns can be any of following types
    # http:Ok (The ticket's events, oldest first)
    # http:NotFound (No such ticket)
    resource function get tickets/[string ticketId]/events() returns inline_response_200_1|ErrorNotFound|error {
        TicketRow?|error found = fetchTicketRow(ticketId);
        if found is error {
            return found;
        }
        if found is () {
            return <ErrorNotFound>{body: {code: 404, message: "no such ticket"}};
        }

        TicketEventRow[] rows = check listTicketEventRows(ticketId);
        TicketEvent[] events = [];
        foreach TicketEventRow row in rows {
            events.push(toApiTicketEvent(row));
        }
        inline_response_200_1 result = {count: events.length(), data: events};
        return result;
    }

    # Submit a new ticket (external ticketing systems)
    #
    # + X\-Api\-Key - Shared ingestion credential issued to the submitting system
    # + return - returns can be any of following types
    # http:Created (Ticket accepted and queued for triage)
    # http:BadRequest (Missing or invalid ticket fields)
    # http:Unauthorized (Missing or invalid ingestion credential)
    resource function post tickets(@http:Header string X\-Api\-Key, @http:Payload TicketSubmission payload)
            returns Ticket|ErrorBadRequest|ErrorUnauthorized|error {
        if X\-Api\-Key != ingestionApiKey {
            return <ErrorUnauthorized>{body: {code: 401, message: "missing or invalid ingestion credential"}};
        }

        string subject = payload.subject.trim();
        string body = payload.body.trim();
        if subject == "" || body == "" {
            return <ErrorBadRequest>{body: {code: 400, message: "subject and body are required"}};
        }

        string ticketId = newTicketId();
        string? sourceSystem = payload?.sourceSystem;
        check insertTicket(ticketId, sourceSystem, payload.subject, payload.body);
        check insertTicketEvent(ticketId, "submitted", ());

        TriageResult|error classifyResult = classifyTicket(ticketId, payload.subject, payload.body);
        if classifyResult is error {
            error? cleanupError = deleteTicketCascade(ticketId);
            if cleanupError is error {
                log:printError("failed to roll back ticket after triage failure", 'error = cleanupError,
                    ticketId = ticketId);
            }
            log:printError("triage-agent classification failed", 'error = classifyResult, ticketId = ticketId);
            return error("triage-agent classification failed", cause = classifyResult);
        }

        string? classifiedUrgency = classifyResult.urgency;
        if classifiedUrgency is () {
            // classifyTicket already guarantees this is non-nil; guarded again for type-safety.
            return error("triage-agent did not return an urgency classification");
        }
        check classifyTicketRow(ticketId, classifiedUrgency, classifyResult.draftReply, classifyResult.conversationId);
        check insertTicketEvent(ticketId, "classified", classifiedUrgency);
        check insertTicketEvent(ticketId, "drafted", ());

        TicketRow?|error finalRow = fetchTicketRow(ticketId);
        if finalRow is error {
            return finalRow;
        }
        if finalRow is () {
            return error("ticket disappeared after triage");
        }
        Ticket ticket = check toApiTicket(finalRow);
        return ticket;
    }

    # Approve the drafted reply
    #
    # + return - returns can be any of following types
    # http:Ok (Ticket marked approved)
    # http:NotFound (No such ticket)
    # http:BadRequest (Ticket is not in a state that can be approved)
    resource function post tickets/[string ticketId]/approve() returns TicketOk|ErrorNotFound|ErrorBadRequest|error {
        TicketRow?|error found = fetchTicketRow(ticketId);
        if found is error {
            return found;
        }
        if found is () {
            return <ErrorNotFound>{body: {code: 404, message: "no such ticket"}};
        }
        if found.status != "triaged" {
            return <ErrorBadRequest>{body: {code: 400, message: "ticket is not in a state that can be approved"}};
        }

        check markApproved(ticketId);
        check insertTicketEvent(ticketId, "approved", ());

        TicketRow?|error updated = fetchTicketRow(ticketId);
        if updated is error {
            return updated;
        }
        if updated is () {
            return error("ticket disappeared after approval");
        }
        Ticket ticket = check toApiTicket(updated);
        return <TicketOk>{body: ticket};
    }

    # Reject the drafted reply and request a new one
    #
    # + return - returns can be any of following types
    # http:Ok (Ticket marked rejected and a new draft requested)
    # http:NotFound (No such ticket)
    # http:BadRequest (Ticket is not in a state that can be rejected)
    resource function post tickets/[string ticketId]/reject() returns TicketOk|ErrorNotFound|ErrorBadRequest|error {
        TicketRow?|error found = fetchTicketRow(ticketId);
        if found is error {
            return found;
        }
        if found is () {
            return <ErrorNotFound>{body: {code: 404, message: "no such ticket"}};
        }
        if found.status != "triaged" {
            return <ErrorBadRequest>{body: {code: 400, message: "ticket is not in a state that can be rejected"}};
        }

        string? conversationId = found.triageConversationId;
        if conversationId is () {
            return error("ticket has no triage conversation to redraft against");
        }

        TriageResult|error redraftResult = redraftTicket(ticketId, conversationId);
        if redraftResult is error {
            log:printError("triage-agent redraft failed", 'error = redraftResult, ticketId = ticketId);
            return error("triage-agent redraft failed", cause = redraftResult);
        }

        // NOTE (flagged for PR review): specs/validation/acceptance/queue-review-and-approval.feature's
        // story-6 scenario asserts the ticket's status is "rejected" right after this call, which
        // conflicts with domain-model.md ("...a rejection asks the agent for a new draft and returns
        // to triaged") and issue #7's own acceptance text. Implemented per domain-model.md + issue #7:
        // the final status here is "triaged", not "rejected".
        check insertTicketEvent(ticketId, "rejected", ());
        check applyRedraft(ticketId, redraftResult.urgency, redraftResult.draftReply);
        check insertTicketEvent(ticketId, "drafted", ());

        TicketRow?|error updated = fetchTicketRow(ticketId);
        if updated is error {
            return updated;
        }
        if updated is () {
            return error("ticket disappeared after reject");
        }
        Ticket ticket = check toApiTicket(updated);
        return <TicketOk>{body: ticket};
    }

    # Override the AI-assigned urgency level
    #
    # + return - returns can be any of following types
    # http:Ok (Urgency updated)
    # http:NotFound (No such ticket)
    resource function post tickets/[string ticketId]/urgency(@http:Payload ticketId_urgency_body payload)
            returns TicketOk|ErrorNotFound|error {
        TicketRow?|error found = fetchTicketRow(ticketId);
        if found is error {
            return found;
        }
        if found is () {
            return <ErrorNotFound>{body: {code: 404, message: "no such ticket"}};
        }

        check updateUrgencyOverride(ticketId, payload.urgency);
        check insertTicketEvent(ticketId, "urgency-overridden", payload.urgency);

        TicketRow?|error updated = fetchTicketRow(ticketId);
        if updated is error {
            return updated;
        }
        if updated is () {
            return error("ticket disappeared after urgency override");
        }
        Ticket ticket = check toApiTicket(updated);
        return <TicketOk>{body: ticket};
    }

    # Edit the drafted reply text
    #
    # + return - returns can be any of following types
    # http:Ok (Draft reply updated)
    # http:NotFound (No such ticket)
    resource function put tickets/[string ticketId]/draft\-reply(@http:Payload ticketId_draftreply_body payload)
            returns Ticket|ErrorNotFound|error {
        TicketRow?|error found = fetchTicketRow(ticketId);
        if found is error {
            return found;
        }
        if found is () {
            return <ErrorNotFound>{body: {code: 404, message: "no such ticket"}};
        }

        check updateDraftReply(ticketId, payload.draftReply);
        check insertTicketEvent(ticketId, "draft-edited", ());

        TicketRow?|error updated = fetchTicketRow(ticketId);
        if updated is error {
            return updated;
        }
        if updated is () {
            return error("ticket disappeared after draft edit");
        }
        Ticket ticket = check toApiTicket(updated);
        return ticket;
    }
}

public type Ticket record {
    string id;
    string sourceSystem?;
    string subject;
    string body;
    Urgency urgency;
    boolean urgencyOverridden?;
    string draftReply?;
    TicketStatus status;
    string createdAt;
    string updatedAt;
};

public type TicketEvent record {
    string id;
    string ticketId;
    # submitted | classified | drafted | urgency-overridden | draft-edited | approved | rejected
    string 'type;
    string detail?;
    string createdAt;
};

public type Error record {
    # HTTP or application error code
    int code;
    # short human-readable label
    string message;
    # detailed explanation
    string description?;
    # URI to documentation
    string moreInfo?;
};

public type ErrorBadRequest record {|
    *http:BadRequest;
    Error body;
|};

public type TicketStatus "new"|"triaged"|"approved"|"rejected";

public type ticketId_urgency_body record {
    Urgency urgency;
};

public type ErrorNotFound record {|
    *http:NotFound;
    Error body;
|};

public type inline_response_200_1 record {
    # total events
    int count;
    # relative URI of the next page
    string? next?;
    # relative URI of the previous page
    string? previous?;
    TicketEvent[] data;
};

public type inline_response_200 record {
    # total matching tickets
    int count;
    # relative URI of the next page
    string? next?;
    # relative URI of the previous page
    string? previous?;
    Ticket[] data;
};

public type ticketId_draftreply_body record {
    string draftReply;
};

public type TicketSubmission record {
    string subject;
    string body;
    # Name of the submitting external system
    string sourceSystem?;
};

public type Urgency "Low"|"Medium"|"High"|"Critical";

public type TicketOk record {|
    *http:Ok;
    Ticket body;
|};

public type ErrorUnauthorized record {|
    *http:Unauthorized;
    Error body;
|};
